//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestingApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emma	Female
        ///Olivia	Female
        ///Noah	Male
        ///Liam	Male
        ///Sophia	Female
        ///Mason	Male
        ///Ava	Female
        ///Jacob	Male
        ///William	Male
        ///Isabella	Female
        ///Ethan	Male
        ///Mia	Female
        ///James	Male
        ///Alexander	Male
        ///Michael	Male
        ///Benjamin	Male
        ///Elijah	Male
        ///Daniel	Male
        ///Aiden	Male
        ///Logan	Male
        ///Matthew	Male
        ///Abigail	Female
        ///Lucas	Male
        ///Jackson	Male
        ///Emily	Female
        ///David	Male
        ///Oliver	Male
        ///Jayden	Male
        ///Joseph	Male
        ///Charlotte	Female
        ///Gabriel	Male
        ///Samuel	Male
        ///Carter	Male
        ///Anthony	Male
        ///John	Male
        ///Harper	Female
        ///Dylan	Male
        ///Luke	Male
        ///Henry	M [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FirstNameDB {
            get {
                return ResourceManager.GetString("FirstNameDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string gavno {
            get {
                return ResourceManager.GetString("gavno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smith
        ///Johnson
        ///Williams
        ///Brown
        ///Jones
        ///Miller
        ///Davis
        ///Garcia
        ///Rodriguez
        ///Wilson
        ///Martinez
        ///Anderson
        ///Taylor
        ///Thomas
        ///Hernandez
        ///Moore
        ///Martin
        ///Jackson
        ///Thompson
        ///White
        ///Lopez
        ///Lee
        ///Gonzalez
        ///Harris
        ///Clark
        ///Lewis
        ///Robinson
        ///Walker
        ///Perez
        ///Hall
        ///Young
        ///Allen
        ///Sanchez
        ///Wright
        ///King
        ///Scott
        ///Green
        ///Baker
        ///Adams
        ///Nelson
        ///Hill
        ///Ramirez
        ///Campbell
        ///Mitchell
        ///Roberts
        ///Carter
        ///Phillips
        ///Evans
        ///Turner
        ///Torres
        ///Parker
        ///Collins
        ///Edwards
        ///Stewart
        ///Flores
        ///Morris
        ///Nguyen
        ///Murphy
        ///Rivera
        ///Cook
        ///Rogers
        ///Morgan
        ///Peterson
        ///Co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LastNameDB {
            get {
                return ResourceManager.GetString("LastNameDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string teststring {
            get {
                return ResourceManager.GetString("teststring", resourceCulture);
            }
        }
    }
}
